### ISSUE TITLE
sd-encrypt password prompt not showing up

### ISSUE THREAD

**Issue by Davincible** [adi1090x/plymouth-themes#19]
sd-encrypt password prompt doesn't show up. Have to press escape to get the regualar startup prompt. It does work with plymouth-encrypt.

As it does work with other themes, (tried manjaro), the issue must be in this theme set specifically

**Comment by berzoidberg** [comment]
This is not a theme issue. Are you using sd-plymouth?

**Comment by Davincible** [comment]
Yup
`HOOKS=(base systemd autodetect sd-plymouth modconf block keyboard sd-vconsole sd-encrypt lvm2 filesystems fsck)`

**Comment by dschemp** [comment]
@Davincible I have setup mkinitcpio hooks as this:
```
HOOKS=(base systemd sd-plymouth autodetect modconf block keyboard sd-vconsole sd-encrypt filesystems fsck)
```
with the default `bgrt` (`spinner` derivate) theme.
What theme did you use? Does is prompt you for your password when using for example `spinner` or `bgrt`.?

**Comment by Davincible** [comment]
@dschemp Can't remember which one I used. Using some completely other, basic theme now

**Comment by jocelynthode** [comment]
I can confirm that I have exactly the same issues as @rickie95 . Using any of the themes here I was never prompted for the password. I have to press escape and fallback to TTY to enter the password.
With the classic BGRT theme it works perfectly.

**Comment by SteveGremory** [comment]
same here, at least with the themes i tried (some from pack 4)

**Comment by dejor** [comment]
I had the same issue on Manjaro with KDE and the `colorful_loop` theme from pack_1.
I am using the [plymouth-git](https://aur.archlinux.org/packages/plymouth-git) package from the AUR.

The problem was, that the initramfs did not include label.so and a font to use.

### Fix
Only works for [plymouth-git](https://aur.archlinux.org/packages/plymouth-git) or [plymouth](https://aur.archlinux.org/packages/plymouth) from the AUR.
Install the optional dependency [ttf-dejavu](https://archlinux.org/packages/?q=ttf-dejavu) with your preferred package manager, e.g.:
```
sudo pacman -S ttf-dejavu
```

**Comment by sp4rq-dev** [comment]
> I had the same issue on Manjaro with KDE and the `colorful_loop` theme from pack_1.
> I am using the [plymouth-git](https://aur.archlinux.org/packages/plymouth-git) package from the AUR.
> 
> The problem was, that the initramfs did not include `/usr/lib/plymouth/label.so` and no font to use.
> 
> ### Fix
> Only works for [plymouth-git](https://aur.archlinux.org/packages/plymouth-git) or [plymouth](https://aur.archlinux.org/packages/plymouth) from the AUR.
> Install the optional dependency [ttf-dejavu](https://archlinux.org/packages/?q=ttf-dejavu) with your preferred package manager, e.g.:
> ```
> sudo pacman -S ttf-dejavu
> ```
> Now the label.so lib and the ttf-dejavu font should be added to the initramfs by the plymouth or the sd-plymouth hook.

Thanks it works for me. Also after installing the ttf-dejavu package you have to rebuild the theme.
```
plymouth-set-default-theme -R your-theme
```

**Comment by TheRedCyclops** [comment]
This seems to be broken again, I have just tested with sd-encrypt and no themes from this pack seem to work (I haven't tested all of them, but the code seems to be the same for all of them), but the default that come with the plymouth package do work

**Comment by dejor** [comment]
The issue could be, that the [plymouth](https://archlinux.org/packages/extra/x86_64/plymouth/) package for arch now requires a `Font` in the `theme.plymouth` file.
See: https://gitlab.archlinux.org/archlinux/packaging/packages/plymouth/-/blob/main/plymouth.initcpio_install?ref_type=heads#L9

I don't have any issues, since the output of `fc-match ""` is `NotoSans-Regular.ttf: "Noto Sans" "Regular"` on my system.

**Comment by TheRedCyclops** [comment]
fc-match "" outputs the same thing in my system, And I have literally all the fonts available in the main repository installed
